### ISSUE TITLE
add.txt 添加路由是走跃点最小的网关吗？

### ISSUE THREAD

**Issue by aglent** [HMBSbige/getcnIP#1]
我看到add.txt里的内容是
add 1.0.1.0 mask 255.255.255.0 default METRIC default IF default
测试了下  自动添加的路由 走的是METRIC最小的网卡
我想自己选择网关 请问如何修改？是把第一个default改成指定的网关吗？  IF default可以去掉？

**Comment by HMBSbige** [comment]
抱歉其实我自己也想问，查了很多资料只知道这样调用cmroute.dll。每次我都是先导入路由表再开启VPN。如果要在windows自己选择网关，可以用route add命令，不过很慢。
如果你知道怎么用cmroute.dll自定义网关的话，希望能告诉我，谢谢！

**Comment by aglent** [comment]
多谢指点 
我家里电脑有线网卡连电信 无线网卡连移动 无线网卡优先级高
因为电信房访问国外很慢 移动访问国内会插广告 所以我打算国内IP走电信 国外IP走移动 代理也走移动
现在按照你的步骤 只能先加载路由 再enable 无线网卡

**Comment by SkylineLch** [comment]
@HMBSbige 用route print查看自己的真实网卡接口编号。第一个default是网关，第三个是真实网卡的接口编号。
github里还有一个项目https://github.com/lmc999/auto-add-routes 
可以参考一下
